# Generated by Django 5.2.8 on 2025-12-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_booking_duration_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
